language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: R65Mg4EDIn9wTDAgCLtVjMu7ShCL1EudxP/Dvnk8JoEjunj1+fJiyEN1Rh+RvMxIJiZN9A6S/4Iz8v6SKp99gC5NcAucmMk2GCuX8z4oZQiCL+Z9YQcLXVKSBj1KXnW/JZgBVbCmRWYrliNIn7RHYgcr+hE1BJu+3v3Q8UQXPYU=
  - secure: Ntei9+f9aAHDtxeIlwVufExQE4ruY2RRiYMii2OIK8sBP2HK9azGScEOxfZsPVGoH2FzaFPMqLf9XZukmbUGxlmT4jbBphOxhNINi2hNhFiKED95foWEuJVT2GcCnV0UTotRmdRlDPUmoDC2APmEiPRgiIN3s/G+YV22DxGJWaA=
  - secure: V+L6zHpYfASXHRaeP6JaBbElNzqw9wfnH2g9LvCBJ8RQqT5RusxBOIntv4xhNKWG7alAA+s1JHEkrQYOfugY9qq452mwYaVt7jlSp5FVOSCis6t4J8mrtNDANx3NrF/Ghyy+zStlY7ds1kpUX3oo1hYI7Bxrd/ZliCI+4tBuJgk=
  - secure: PWdSYhgl2nploB49hb+zExed1q5XtSZ/W893fopbfbWj/GyjFfLvaeKeIsuqmL27mBsAL5Kncd76hEWHrFSX/1iF4lzWRJoT27iFbEN7D2E30Nia0/l88N47F5f+8B60SjCju2H0WRUj7xfj/UuPIIUin7B/EdgoSwPgDaTJU5M=
